build:
    environment:
        php: 7.4
    tests:
        override:
            - php-scrutinizer-run

filter:
    excluded_paths:
        - tests/
    dependency_paths:
        - vendor/

checks:
    php: true

tools:
    external_code_coverage: true
