language: php

php:
    - 7.0
    - 7.1

install:
    - composer install -n

script:
    - ./bin/phpunit --coverage-clover=coverage.clover
    - wget https://scrutinizer-ci.com/ocular.phar
    - if [[ "$(phpenv version-name)" == "7.0" ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
